language: java
sudo: false
cache:
  directories:
    - .autoconf
    - $HOME/.m2
jdk:
  - openjdk11

jobs:
  include:
    - stage: build test deploy
      script:
        - mvn -B -V clean install jacoco:report
after_success:
  - bash <(curl -s https://codecov.io/bash)
