language: java
sudo: false
cache:
  directories:
    - .autoconf
    - $HOME/.m2

services:
  - docker

jdk:
  - openjdk11

jobs:
  include:
    - stage: build java
      script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: test
      script: mvn test -B
    - stage: build docker
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t bhuism/citaten:latest .
        - docker push bhuism/citaten:latest
