spring:
  r2dbc:
    url: r2dbc:h2:mem:///demo?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    schema: classpath:schema.sql
    data: classpath:bigdata.sql
    initialization-mode: always
  resources:
    chain:
      cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /webjars/**
    cache:
      period: 86400
      cachecontrol:
        cache-public: true
  output:
    ansi:
      enabled: detect
  main:
    banner-mode: log
  cloud:
    gcp:
      logging:
        enabled: false
      trace:
        enabled: false
server:
  compression:
    enabled: true
  forward-headers-strategy: framework
logging:
  level:
    nl.appsource: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
