spring:
  r2dbc:
    schema: classpath:schema.sql
    data: classpath:bigdata.sql
    initialization-mode: always
server:
  tomcat:
    accesslog:
      enabled: true
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
