server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'info,health'
spring:
  cloud:
    gcp:
      logging:
        enabled: true
      trace:
        enabled: true
